actors:
  <PrimaryActorName>.php:
    template: PrimaryActorName.php
    annotation_processors:
      DaoPropertiesAndAccessors:
        processor_fqcn: \Neighborhoods\Prefab\AnnotationProcessor\DAO
        static_context_record:
          - name: tableName
            type: string
          - name: daoIdentityField
            type: string
          - name: daoPropertyMap
            type: \Neighborhoods\Prefab\DaoProperty\MapInterface
          - name: rootSaveLocation
            type: string
          - name: projectName
            type: string
          - name: httpRoute
            type: string
          - name: httpVerbs
            type: array
          - name: projectDir
            type: string
          - name: supportingActorGroup
            type: string
          - name: constantMap
            type: \Neighborhoods\Prefab\Constant\MapInterface
  <PrimaryActorName>.service.yml:
    template: PrimaryActorName.service.yml
  <PrimaryActorName>Interface.php:
    template: PrimaryActorNameInterface.php
    annotation_processors:
      DaoAccessors:
        processor_fqcn: \Neighborhoods\Prefab\AnnotationProcessor\DAOInterface
        static_context_record:
        - name: tableName
          type: string
        - name: daoIdentityField
          type: string
        - name: daoPropertyMap
          type: \Neighborhoods\Prefab\DaoProperty\MapInterface
        - name: projectName
          type: string
        - name: rootSaveLocation
          type: string
        - name: httpRoute
          type: string
        - name: httpRoute
          type: string
        - name: httpRoute
          type: string
        - name: httpVerbs
          type: array
        - name: projectDir
          type: string
        - name: supportingActorGroup
          type: string
        - name: constantMap
          type: \Neighborhoods\Prefab\Constant\MapInterface
  <PrimaryActorName>/AwareTrait.php:
    template: PrimaryActorName/Awaretrait.php
  <PrimaryActorName>/Factory.php:
    template: PrimaryActorName/Factory.php
  <PrimaryActorName>/Factory.service.yml:
    template: PrimaryActorName/Factory.service.yml
  <PrimaryActorName>/FactoryInterface.php:
    template: PrimaryActorName/FactoryInterface.php
  <PrimaryActorName>/Factory/AwareTrait.php:
    template: PrimaryActorName/Factory/Awaretrait.php
  <PrimaryActorName>/Map/Factory.php:
    template: PrimaryActorName/Map/Factory.php
  <PrimaryActorName>/Map/Factory.service.yml:
    template: PrimaryActorName/Map/Factory.service.yml
  <PrimaryActorName>/Map/FactoryInterface.php:
    template: PrimaryActorName/Map/FactoryInterface.php
  <PrimaryActorName>/Map.php:
    template: PrimaryActorName/Map.php
  <PrimaryActorName>/Map/AwareTrait.php:
    template: PrimaryActorName/Map/AwareTrait.php
  <PrimaryActorName>/Map.service.yml:
    template: PrimaryActorName/Map.service.yml
  <PrimaryActorName>/MapInterface.php:
    template: PrimaryActorName/MapInterface.php
